
  0%|          | 0/1000 [00:01<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/josyula/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/josyula/miniconda3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/josyula/Programs/MAS_Project/test/evostrat/evostrat/population.py", line 79, in _fitness_fn_no_grad
    return ind.fitness()
  File "/home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/evolvestrategies/MRCarry.py", line 79, in fitness
    dist_goal, dist_robots = self.dist2goal(obs)
AttributeError: 'MRCarry' object has no attribute 'dist2goal'
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4abf4ddbc274>", line 1, in <module>
    runfile('/home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/evolvestrategies/multirobot_carry_evo.py', wdir='/home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/evolvestrategies')
  File "/home/josyula/Programs/pycharm-2022.2.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/josyula/Programs/pycharm-2022.2.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/evolvestrategies/multirobot_carry_evo.py", line 31, in <module>
    raw_fit = population.fitness_grads(pop_size, pool, compute_centered_ranks)
  File "/home/josyula/Programs/MAS_Project/test/evostrat/evostrat/population.py", line 65, in fitness_grads
    raw_fitness = pool.map(_fitness_fn_no_grad, individuals)
  File "/home/josyula/miniconda3/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/josyula/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
