2022-11-20 20:39:24,862 INFO    MainThread:11063 [wandb_setup.py:_flush():71] setting env: {}
2022-11-20 20:39:24,862 INFO    MainThread:11063 [wandb_setup.py:_flush():71] setting login settings: {}
2022-11-20 20:39:24,862 INFO    MainThread:11063 [wandb_init.py:_log_setup():371] Logging user logs to /home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/wandb/run-20221120_203924-3jnc7p9s/logs/debug.log
2022-11-20 20:39:24,862 INFO    MainThread:11063 [wandb_init.py:_log_setup():372] Logging internal logs to /home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/wandb/run-20221120_203924-3jnc7p9s/logs/debug-internal.log
2022-11-20 20:39:24,862 INFO    MainThread:11063 [wandb_init.py:init():404] calling init triggers
2022-11-20 20:39:24,862 INFO    MainThread:11063 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-11-20 20:39:24,862 INFO    MainThread:11063 [wandb_init.py:init():460] starting backend
2022-11-20 20:39:24,863 INFO    MainThread:11063 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-11-20 20:39:24,871 INFO    MainThread:11063 [backend.py:ensure_launched():216] starting backend process...
2022-11-20 20:39:24,876 INFO    MainThread:11063 [backend.py:ensure_launched():221] started backend process with pid: 11100
2022-11-20 20:39:24,877 INFO    MainThread:11063 [wandb_init.py:init():469] backend started and connected
2022-11-20 20:39:24,880 INFO    MainThread:11063 [wandb_init.py:init():533] updated telemetry
2022-11-20 20:39:24,891 INFO    MainThread:11063 [wandb_init.py:init():563] communicating current version
2022-11-20 20:39:26,023 INFO    MainThread:11063 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.13.5 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-11-20 20:39:26,023 INFO    MainThread:11063 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-11-20 20:39:26,237 INFO    MainThread:11063 [wandb_init.py:init():606] starting run threads in backend
2022-11-20 20:39:31,243 INFO    MainThread:11063 [wandb_run.py:_console_start():1810] atexit reg
2022-11-20 20:39:31,244 INFO    MainThread:11063 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-11-20 20:39:31,244 INFO    MainThread:11063 [wandb_run.py:_redirect():1689] Redirecting console.
2022-11-20 20:39:31,247 INFO    MainThread:11063 [wandb_run.py:_redirect():1745] Redirects installed.
2022-11-20 20:39:31,247 INFO    MainThread:11063 [wandb_init.py:init():633] run started, returning control to user process
2022-11-20 20:39:31,763 INFO    MainThread:11063 [wandb_setup.py:_flush():71] setting env: {}
2022-11-20 20:39:31,763 INFO    MainThread:11063 [wandb_setup.py:_flush():71] setting login settings: {}
2022-11-20 20:39:31,763 INFO    MainThread:11063 [wandb_init.py:_log_setup():371] Logging user logs to /home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/wandb/run-20221120_203931-1cgu6g9l/logs/debug.log
2022-11-20 20:39:31,763 INFO    MainThread:11063 [wandb_init.py:_log_setup():372] Logging internal logs to /home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/wandb/run-20221120_203931-1cgu6g9l/logs/debug-internal.log
2022-11-20 20:39:31,763 INFO    MainThread:11063 [wandb_init.py:init():404] calling init triggers
2022-11-20 20:39:31,763 INFO    MainThread:11063 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-11-20 20:39:31,763 INFO    MainThread:11063 [wandb_init.py:init():455] wandb.init() called when a run is still active
2022-11-20 20:54:22,124 INFO    MainThread:11063 [wandb_run.py:_atexit_cleanup():1771] got exitcode: 0
2022-11-20 20:54:22,125 INFO    MainThread:11063 [wandb_run.py:_restore():1751] restore
2022-11-20 20:54:23,126 INFO    MainThread:11063 [wandb_run.py:_restore():1751] restore
2022-11-20 20:54:27,516 ERROR   MainThread:11063 [wandb_run.py:_atexit_cleanup():1771] Problem finishing run
Traceback (most recent call last):
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1771, in _atexit_cleanup
    def _atexit_cleanup(self, exit_code: int = None) -> None:
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1923, in _on_finish
    def _on_finish(self) -> None:
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1827, in _console_stop
    def _console_stop(self) -> None:
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1751, in _restore
    def _restore(self) -> None:
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 727, in uninstall
    def uninstall(self):
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 506, in src_fd
    @property
ValueError: I/O operation on closed file
