2022-11-25 16:47:35,652 INFO    MainThread:26121 [wandb_setup.py:_flush():71] setting env: {}
2022-11-25 16:47:35,652 INFO    MainThread:26121 [wandb_setup.py:_flush():71] setting login settings: {}
2022-11-25 16:47:35,652 INFO    MainThread:26121 [wandb_init.py:_log_setup():371] Logging user logs to /home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/neurocoevolution_pytorch/wandb/run-20221125_164735-1p5rdkd3/logs/debug.log
2022-11-25 16:47:35,652 INFO    MainThread:26121 [wandb_init.py:_log_setup():372] Logging internal logs to /home/josyula/Programs/MAS_Project/gym_envs_urdf/examples/neurocoevolution_pytorch/wandb/run-20221125_164735-1p5rdkd3/logs/debug-internal.log
2022-11-25 16:47:35,653 INFO    MainThread:26121 [wandb_init.py:init():404] calling init triggers
2022-11-25 16:47:35,653 INFO    MainThread:26121 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-11-25 16:47:35,653 INFO    MainThread:26121 [wandb_init.py:init():460] starting backend
2022-11-25 16:47:35,653 INFO    MainThread:26121 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-11-25 16:47:35,668 INFO    MainThread:26121 [backend.py:ensure_launched():216] starting backend process...
2022-11-25 16:47:35,674 INFO    MainThread:26121 [backend.py:ensure_launched():221] started backend process with pid: 26205
2022-11-25 16:47:35,676 INFO    MainThread:26121 [wandb_init.py:init():469] backend started and connected
2022-11-25 16:47:35,679 INFO    MainThread:26121 [wandb_init.py:init():533] updated telemetry
2022-11-25 16:47:35,696 INFO    MainThread:26121 [wandb_init.py:init():563] communicating current version
2022-11-25 16:47:36,738 INFO    MainThread:26121 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.13.5 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-11-25 16:47:36,739 INFO    MainThread:26121 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-11-25 16:47:36,918 INFO    MainThread:26121 [wandb_init.py:init():606] starting run threads in backend
2022-11-25 16:47:41,924 INFO    MainThread:26121 [wandb_run.py:_console_start():1810] atexit reg
2022-11-25 16:47:41,925 INFO    MainThread:26121 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-11-25 16:47:41,925 INFO    MainThread:26121 [wandb_run.py:_redirect():1689] Redirecting console.
2022-11-25 16:47:41,927 INFO    MainThread:26121 [wandb_run.py:_redirect():1745] Redirects installed.
2022-11-25 16:47:41,928 INFO    MainThread:26121 [wandb_init.py:init():633] run started, returning control to user process
2022-11-25 16:49:33,111 INFO    MainThread:26121 [wandb_run.py:_atexit_cleanup():1771] got exitcode: 0
2022-11-25 16:49:33,113 INFO    MainThread:26121 [wandb_run.py:_restore():1751] restore
2022-11-25 16:49:34,115 INFO    MainThread:26121 [wandb_run.py:_restore():1751] restore
2022-11-25 16:49:38,686 ERROR   MainThread:26121 [wandb_run.py:_atexit_cleanup():1771] Problem finishing run
Traceback (most recent call last):
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1771, in _atexit_cleanup
    def _atexit_cleanup(self, exit_code: int = None) -> None:
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1923, in _on_finish
    def _on_finish(self) -> None:
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1827, in _console_stop
    def _console_stop(self) -> None:
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1751, in _restore
    def _restore(self) -> None:
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 727, in uninstall
    def uninstall(self):
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 506, in src_fd
    @property
ValueError: I/O operation on closed file
